<?php
/**
 * /admin/api-keys/new -- form for a new API key.
 *
 * Provided by ApiKeysController::create():
 *   $pageTitle  string
 *   $csrf       string
 *   $flash      list<{type,message}>
 */
?>

<div class="flex items-center justify-between mb-6">
    <div>
        <h1 class="text-2xl font-bold text-gray-100">New API Key</h1>
        <p class="text-sm text-gray-400 mt-1">
            Generated by the server; you'll see the plaintext exactly once.
        </p>
    </div>
    <a href="/admin/api-keys" class="text-sm text-gray-400 hover:text-gray-200">Back to keys</a>
</div>

<?php require dirname(__DIR__, 2) . '/partials/flash.php'; ?>

<div class="bg-white rounded-lg shadow p-6 max-w-2xl">
    <form method="POST" action="/admin/api-keys/create" class="space-y-5">
        <input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf, ENT_QUOTES, 'UTF-8') ?>">

        <div>
            <label for="label" class="block text-sm font-medium text-gray-700 mb-1">Label</label>
            <input type="text"
                   id="label"
                   name="label"
                   maxlength="100"
                   required
                   placeholder="Mobile app v1 / CI deploy / Partner X"
                   class="w-full px-3 py-2 border border-gray-300 rounded shadow-sm focus:outline-none focus:ring focus:ring-blue-200">
            <p class="text-xs text-gray-500 mt-1">For your reference. Shown in the list view next to the key hash.</p>
        </div>

        <div>
            <span class="block text-sm font-medium text-gray-700 mb-1">Scope</span>
            <div class="space-y-2">
                <label class="flex items-start gap-2 cursor-pointer">
                    <input type="radio" name="scope" value="read" checked class="mt-1">
                    <span>
                        <span class="block text-sm font-medium text-gray-900">read</span>
                        <span class="block text-xs text-gray-500">GET only. List + read content, URL inventory, site config (whitelist).</span>
                    </span>
                </label>
                <label class="flex items-start gap-2 cursor-pointer">
                    <input type="radio" name="scope" value="write" class="mt-1">
                    <span>
                        <span class="block text-sm font-medium text-gray-900">write</span>
                        <span class="block text-xs text-gray-500">All verbs. Create/update/delete content, mutate URL meta + site config (still whitelisted), upload assets.</span>
                    </span>
                </label>
            </div>
        </div>

        <div class="pt-2 flex items-center gap-3">
            <button type="submit"
                    class="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-sm font-medium rounded">
                Generate key
            </button>
            <a href="/admin/api-keys" class="text-sm text-gray-500 hover:text-gray-800">Cancel</a>
        </div>
    </form>
</div>

<div class="mt-6 max-w-2xl text-xs text-gray-400">
    The key is generated as <code class="font-mono">bin2hex(random_bytes(32))</code> -- 64-character hex.
    The plaintext is shown ONCE on the next screen; only the SHA-256 hash is persisted to
    <code class="font-mono">storage/api-keys.json</code>. Lost keys must be revoked and replaced.
</div>
